# Generates bart_panel/portal_html.h from web/portal.html and web/default_template.json.
# Run after editing either file, before compiling.
$root = Split-Path $PSScriptRoot -Parent
$html = [IO.File]::ReadAllText((Join-Path $root "web\portal.html"))
$tpl = [IO.File]::ReadAllText((Join-Path $root "web\default_template.json"))
foreach ($s in $html, $tpl) {
  if ($s.Contains(')WEB"')) { throw 'web file contains the raw-string delimiter )WEB"' }
}
$out = @"
#pragma once
// Generated by tools/embed_web.ps1 from web/. Do not edit.
static const char PORTAL_HTML[] PROGMEM = R"WEB($html)WEB";
static const char DEFAULT_TEMPLATE[] PROGMEM = R"WEB($tpl)WEB";
"@
[IO.File]::WriteAllText((Join-Path $root "bart_panel\portal_html.h"), $out)
"wrote bart_panel/portal_html.h"
